# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-18 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161011_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='real_last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
