# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-19 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_userprofile_real_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
