# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-20 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_userprofile_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.FileField(null=True, upload_to='profile_image'),
        ),
    ]
