# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-21 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_article_collectors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='collectors',
            field=models.ManyToManyField(blank=True, null=True, to='blog.UserProfile'),
        ),
    ]
