# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-21 17:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20161022_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='collectors',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
