# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-23 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20161022_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], max_length=5, null=True),
        ),
    ]
